In [155]:
# First we load the packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

# I. Data Preparation

In [156]:
# Read in master data
# Note this master dataset was created in the Week 2 assignment
Master = pd.read_csv("D:\\GitHub\\Coursera\\SportsPerformanceAnalytics\\MoneyBallAndBeyond\\data\\Master.csv")

In [157]:
#Your Code Here

Master['Exp2']= Master['Exp']**2

In [158]:
print(Master.columns.tolist())

['Unnamed: 0', 'playerID', 'yearID', 'stint', 'G', 'AB', 'R', 'H', 'Doubles', 'Triples', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP', 'PA', 'OBP', 'SLG', 'SalYear', 'teamID', 'lgID', 'salary', 'lnSal', 'debutyr', 'Exp', 'Arb', 'Free', 'POS', 'Catch', 'Infld', 'Exp2']

In [159]:
Master['BA'] = Master['H']/Master['AB']
Master['ISO_POWER'] = Master['SLG']-Master['BA']
Master['EYE'] = (Master['BB']+Master['HBP'])/Master['PA']

In [160]:
Master_95_15 = Master[(Master.SalYear >= 1995) & (Master.SalYear <= 2015)]

In [161]:
#### Quiz 1 Work below this cell ####

In [162]:
print(max(Master_95_15['EYE']))

0.3905996758508914

In [163]:
Master_95_15

,Unnamed: 0,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,...,Exp,Arb,Free,POS,Catch,Infld,Exp2,BA,ISO_POWER,EYE
0,0,abbotje01,1998,1,89,244,33,68,14,1,...,1,0,0,OF,0,0,1,0.278689,0.213115,0.034615
1,1,abbotje01,2000,1,80,215,31,59,15,1,...,3,1,0,OF,0,0,9,0.274419,0.120930,0.095436
2,2,abbotku01,1994,1,101,345,41,86,17,3,...,1,0,0,SS,0,1,1,0.249275,0.144928,0.056604
3,3,abbotku01,1995,1,120,420,60,107,18,7,...,2,0,0,SS,0,1,4,0.254762,0.197619,0.087607
4,4,abbotku01,1996,1,109,320,37,81,18,7,...,3,1,0,SS,0,1,9,0.253125,0.175000,0.071633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7778,7778,zobribe01,2012,1,157,560,88,151,39,7,...,6,1,0,OF,0,0,36,0.269643,0.201786,0.149701
7779,7779,zobribe01,2013,1,157,612,77,168,36,3,...,7,0,1,2B,0,1,49,0.274510,0.127451,0.113181
7780,7780,zobribe01,2014,1,146,570,83,155,34,3,...,8,0,1,2B,0,1,64,0.271930,0.122807,0.116208
7782,7782,zuninmi01,2013,1,52,173,22,37,5,0,...,0,0,0,C,1,0,0,0.213873,0.115607,0.098446
7783,7783,zuninmi01,2014,1,131,438,51,87,20,2,...,1,0,0,C,1,0,1,0.198630,0.205479,0.071429

In [164]:
Master_95_15['yearID']

0       1998
1       2000
2       1994
3       1995
4       1996
        ...
7778    2012
7779    2013
7780    2014
7782    2013
7783    2014
Name: yearID, Length: 7123, dtype: int64

In [165]:
Master_95_15['teamID']

0       CHA
1       FLO
2       FLO
3       FLO
4       FLO
       ...
7778    TBA
7779    TBA
7780    OAK
7782    SEA
7783    SEA
Name: teamID, Length: 7123, dtype: object

In [166]:
AVG_ISO = Master_95_15.groupby(['yearID','teamID'])['ISO_POWER'].mean()

In [167]:
AVG_ISO

yearID  teamID
1994    ATL       0.191337
        BAL       0.172614
        BOS       0.176837
        CAL       0.150728
        CHA       0.150565
                    ...
2014    SLN       0.129782
        TBA       0.141659
        TEX       0.127361
        TOR       0.148660
        WAS       0.124803
Name: ISO_POWER, Length: 624, dtype: float64

In [168]:
Master_95_15 = pd.merge(Master_95_15, AVG_ISO, on=['yearID', 'teamID'])
Master_95_15 = Master_95_15.rename({'ISO_POWER_x':'ISO_POWER', 'ISO_POWER_y':'AVG_ISO_POWER' })
Master_95_15

,Unnamed: 0,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,...,Arb,Free,POS,Catch,Infld,Exp2,BA,ISO_POWER_x,EYE,ISO_POWER_y
0,0,abbotje01,1998,1,89,244,33,68,14,1,...,0,0,OF,0,0,1,0.278689,0.213115,0.034615,0.149645
1,1206,carusmi01,1998,1,133,523,81,160,17,6,...,0,0,SS,0,1,0,0.305927,0.084130,0.037838,0.149645
2,1961,durhara01,1998,1,158,635,126,181,35,8,...,1,0,2B,0,1,9,0.285039,0.170079,0.109267,0.149645
3,2301,fordybr01,1998,1,57,146,8,37,9,0,...,1,0,C,1,0,9,0.253425,0.123288,0.069620,0.149645
4,3592,jacksda03,1998,1,114,204,20,49,13,1,...,0,1,OF,0,0,169,0.240196,0.132353,0.046729,0.149645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7118,5945,redmati01,2003,1,56,230,36,76,16,5,...,1,0,OF,0,0,9,0.330435,0.152174,0.064516,0.155439
7119,6546,simonra01,2003,3,124,410,47,113,17,0,...,1,0,1B,0,0,36,0.275610,0.158537,0.046404,0.155439
7120,6807,stynech01,2003,1,138,443,71,113,31,3,...,0,1,3B,0,1,64,0.255079,0.158014,0.107570,0.155439
7121,7572,wilsocr03,2003,1,116,309,49,81,15,4,...,0,0,OF,0,0,4,0.262136,0.249191,0.134078,0.155439
7122,7593,wilsoja02,2003,1,150,558,58,143,21,3,...,0,0,SS,0,1,4,0.256272,0.096774,0.065041,0.155439

In [169]:
max_ISO = max(Master_95_15['ISO_POWER_y'])
max_ISO

0.20978181221652709

In [170]:
print(Master_95_15[Master_95_15.ISO_POWER_y == 0.20978181221652709])

      Unnamed: 0   playerID  yearID  stint    G   AB   R    H  Doubles  \
1397         153  anderbr03    2008      1  109  181  24   42       13
1398         605  betemwi01    2008      1   87  189  24   50       13
1399        1983    dyeje01    2008      1  154  590  96  172       41
1400        4051  konerpa01    2008      1  122  438  59  105       19
1401        5703  pierzaj01    2008      1  134  534  66  150       31
1402        5824  quentca01    2008      1  130  480  96  138       26
1403        5856  ramiral03    2008      1  136  480  65  139       22
1404        7012  thomeji01    2008      1  149  503  93  123       28

      Triples  ...  Arb  Free  POS  Catch  Infld  Exp2        BA  ISO_POWER_x  \
1397        0  ...    1     0   OF      0      0     9  0.232044     0.204420
1398        0  ...    0     1   1B      0      0    49  0.264550     0.164021
1399        2  ...    0     1   OF      0      0   144  0.291525     0.249153
1400        1  ...    0     1   1B      0      0   121  0.239726     0.198630
1401        1  ...    0     1    C      1      0   100  0.280899     0.134831
1402        1  ...    0     0   OF      0      0     4  0.287500     0.283333
1403        2  ...    0     0   2B      0      1     0  0.289583     0.185417
1404        0  ...    0     1   DH      0      0   289  0.244533     0.258449

           EYE  ISO_POWER_y
1397  0.051813     0.209782
1398  0.035354     0.209782
1399  0.077519     0.209782
1400  0.140078     0.209782
1401  0.047368     0.209782
1402  0.151142     0.209782
1403  0.041257     0.209782
1404  0.157807     0.209782

[8 rows x 41 columns]

In [171]:
Master_95_15

,Unnamed: 0,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,...,Arb,Free,POS,Catch,Infld,Exp2,BA,ISO_POWER_x,EYE,ISO_POWER_y
0,0,abbotje01,1998,1,89,244,33,68,14,1,...,0,0,OF,0,0,1,0.278689,0.213115,0.034615,0.149645
1,1206,carusmi01,1998,1,133,523,81,160,17,6,...,0,0,SS,0,1,0,0.305927,0.084130,0.037838,0.149645
2,1961,durhara01,1998,1,158,635,126,181,35,8,...,1,0,2B,0,1,9,0.285039,0.170079,0.109267,0.149645
3,2301,fordybr01,1998,1,57,146,8,37,9,0,...,1,0,C,1,0,9,0.253425,0.123288,0.069620,0.149645
4,3592,jacksda03,1998,1,114,204,20,49,13,1,...,0,1,OF,0,0,169,0.240196,0.132353,0.046729,0.149645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7118,5945,redmati01,2003,1,56,230,36,76,16,5,...,1,0,OF,0,0,9,0.330435,0.152174,0.064516,0.155439
7119,6546,simonra01,2003,3,124,410,47,113,17,0,...,1,0,1B,0,0,36,0.275610,0.158537,0.046404,0.155439
7120,6807,stynech01,2003,1,138,443,71,113,31,3,...,0,1,3B,0,1,64,0.255079,0.158014,0.107570,0.155439
7121,7572,wilsocr03,2003,1,116,309,49,81,15,4,...,0,0,OF,0,0,4,0.262136,0.249191,0.134078,0.155439
7122,7593,wilsoja02,2003,1,150,558,58,143,21,3,...,0,0,SS,0,1,4,0.256272,0.096774,0.065041,0.155439

# II. Running Regressions for Each Season

In [172]:
# Write a function to run the Moneyball regression annually for free agents only
def MBExpandFA(Season):
    MB_Seas = Master_95_15[(Master_95_15.SalYear == Season) & (Master_95_15.Free == 1)]
    global lmrate
    lmrate = smf.ols(formula = 'lnSal ~ BA + ISO_POWER_x + EYE + PA + Exp + Exp2 + C(POS)', data=MB_Seas).fit()
    return;

In [173]:
#Your Code Here
index = 0
lmrate_Results = [0]
for index in range(1,21):
    lmrate_Results.append(index)
    index = index + 1
display(lmrate_Results)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [174]:
Season = 1995
i = 0
while Season <= 2015:
    MBExpandFA(Season)
    lmrate_Results[i] = lmrate
    i = i + 1
    Season = Season + 1

In [175]:
Season = 1995
lm_Season = ["1995"]
for Season in range(1996, 2016):
    lm_Season.append(str(Season))
    Season = Season + 1

In [176]:
Pre_MB = lm_Season[:7]
MB_Period = lm_Season[7:14]
Post_MB = lm_Season[14:]

print(Pre_MB)
print(MB_Period)
print(Post_MB)

['1995', '1996', '1997', '1998', '1999', '2000', '2001']
['2002', '2003', '2004', '2005', '2006', '2007', '2008']
['2009', '2010', '2011', '2012', '2013', '2014', '2015']

In [177]:
from statsmodels.iolib.summary2 import summary_col
info_dict={'R-squared' : lambda x: f"{x.rsquared:.2f}",
           'No. observations' : lambda x: f"{int(x.nobs):d}"}

In [178]:
from statsmodels.iolib.summary2 import summary_col
PreMBRate_Out = summary_col([lmrate_Results[0],lmrate_Results[1],lmrate_Results[2],lmrate_Results[3],lmrate_Results[4],
                        lmrate_Results[5],lmrate_Results[6]], model_names=Pre_MB, 
                        regressor_order=['BA','ISO_POWER_x','EYE','PA', 'Exp', 'EXP2'],stars=True,info_dict = info_dict)
print(PreMBRate_Out)

============================================================================================
                    1995      1996       1997       1998       1999       2000       2001
--------------------------------------------------------------------------------------------
BA               3.7261    1.6921     4.4403**   4.0121*    2.8133     2.8979     0.7142
                 (2.4150)  (2.8851)   (2.1651)   (2.1222)   (2.0204)   (1.8524)   (2.1011)
ISO_POWER_x      3.5872*** 4.9581***  2.7886***  3.1340***  2.4689***  3.5986***  5.0715***
                 (1.1991)  (1.3861)   (1.0009)   (1.1908)   (0.9210)   (0.9752)   (1.0084)
EYE              2.4417    0.5096     2.0994     3.8206**   2.0140     1.0060     -3.0326*
                 (1.9611)  (2.0089)   (1.6643)   (1.6066)   (1.5924)   (1.5256)   (1.6224)
PA               0.0062*** 0.0033***  0.0028***  0.0036***  0.0036***  0.0029***  0.0040***
                 (0.0008)  (0.0006)   (0.0004)   (0.0004)   (0.0004)   (0.0004)   (0.0004)
Exp              0.0623    0.0415     -0.1466    0.1424     0.2264*    0.0510     0.1708
                 (0.1612)  (0.2007)   (0.1588)   (0.1502)   (0.1287)   (0.1179)   (0.1122)
Intercept        9.9694*** 11.3986*** 12.2387*** 10.1032*** 10.3032*** 11.7979*** 11.2572***
                 (1.1036)  (1.3914)   (1.0950)   (1.0611)   (0.9596)   (0.8532)   (0.7926)
C(POS)[T.2B]     -0.8179** -0.1286    -0.4298    -0.0151    -0.2160    -0.2726    0.1785
                 (0.3753)  (0.3466)   (0.2642)   (0.2872)   (0.2294)   (0.2175)   (0.2204)
C(POS)[T.3B]     -0.2760   -0.3602    -0.5173*   -0.0798    0.2404     -0.1103    0.2367
                 (0.3050)  (0.3140)   (0.2694)   (0.2479)   (0.2184)   (0.2205)   (0.2175)
C(POS)[T.C]      -0.0799   0.0075     -0.2965    0.1119     -0.0514    -0.0740    0.2604
                 (0.3222)  (0.3241)   (0.2630)   (0.2549)   (0.2281)   (0.2163)   (0.2244)
C(POS)[T.DH]     -0.5695   0.3089     -0.4400    -0.2474    0.1792     -0.3156    -0.2152
                 (0.4073)  (0.4124)   (0.2920)   (0.2946)   (0.2432)   (0.2642)   (0.4206)
C(POS)[T.OF]     -0.3635   0.0120     -0.0859    0.0524     0.1206     -0.0427    0.0307
                 (0.2734)  (0.2673)   (0.2126)   (0.2098)   (0.1772)   (0.1685)   (0.1654)
C(POS)[T.SS]     -0.0890   0.7732**   0.3642     0.0079     0.4419*    -0.0534    -0.1262
                 (0.3385)  (0.3582)   (0.2865)   (0.2863)   (0.2509)   (0.2445)   (0.2403)
Exp2             -0.0018   -0.0030    0.0055     -0.0070    -0.0106*   -0.0027    -0.0072
                 (0.0069)  (0.0085)   (0.0069)   (0.0066)   (0.0055)   (0.0051)   (0.0048)
R-squared        0.5622    0.4700     0.5737     0.5695     0.6544     0.5820     0.6066
R-squared Adj.   0.5081    0.4094     0.5317     0.5318     0.6235     0.5451     0.5734
R-squared        0.56      0.47       0.57       0.57       0.65       0.58       0.61
No. observations 110       118        135        150        147        149        155
============================================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [179]:
from statsmodels.iolib.summary2 import summary_col
MBRate_Out = summary_col([lmrate_Results[7],lmrate_Results[8],lmrate_Results[9],lmrate_Results[10],lmrate_Results[11],
                        lmrate_Results[12],lmrate_Results[13]], model_names=MB_Period, 
                        regressor_order=['BA','ISO_POWER_x','EYE','PA', 'Exp', 'EXP2'],stars=True,info_dict = info_dict)
print(MBRate_Out)

=============================================================================================
                    2002       2003       2004       2005       2006       2007       2008
---------------------------------------------------------------------------------------------
BA               2.2282     2.1671     2.8623     5.1070**   6.1979**   3.6265*    -0.7795
                 (2.6597)   (2.5275)   (2.6710)   (2.2766)   (2.5742)   (2.0114)   (2.0713)
ISO_POWER_x      2.7926**   1.4127     1.8573     3.1916***  2.6517**   3.0405***  3.1244**
                 (1.3380)   (1.3554)   (1.2495)   (1.2057)   (1.2112)   (1.0456)   (1.2600)
EYE              1.7225     3.0337     9.3959***  2.8751     2.9151     4.2304**   3.4829
                 (2.0778)   (2.1865)   (2.1082)   (1.8720)   (2.0959)   (1.8341)   (2.1335)
PA               0.0031***  0.0044***  0.0027***  0.0034***  0.0037***  0.0037***  0.0037***
                 (0.0005)   (0.0005)   (0.0005)   (0.0004)   (0.0005)   (0.0004)   (0.0004)
Exp              0.3620**   0.3474**   0.1630     0.1759     0.0337     0.0690     0.1931
                 (0.1470)   (0.1658)   (0.1522)   (0.1259)   (0.1217)   (0.0947)   (0.1521)
Intercept        10.3452*** 10.0969*** 10.7180*** 10.4152*** 10.6209*** 10.8980*** 11.6518***
                 (1.0372)   (1.1665)   (1.1329)   (0.9773)   (0.9818)   (0.7737)   (0.9852)
C(POS)[T.2B]     -0.0029    -0.2719    0.0510     -0.4057    -0.1014    -0.2304    0.0278
                 (0.2865)   (0.2921)   (0.2977)   (0.2602)   (0.2517)   (0.2269)   (0.2562)
C(POS)[T.3B]     0.2321     0.0073     -0.0236    -0.0976    0.3954*    0.1752     0.5582**
                 (0.3068)   (0.2818)   (0.2966)   (0.2743)   (0.2369)   (0.2308)   (0.2338)
C(POS)[T.C]      0.3305     0.4778*    0.1804     -0.0563    0.2727     0.3856*    0.3537
                 (0.2679)   (0.2740)   (0.2674)   (0.2440)   (0.2383)   (0.2085)   (0.2276)
C(POS)[T.DH]     0.4904     -0.0821    0.2320     0.4188     -0.4248    -0.0662    0.4011
                 (0.3373)   (0.4407)   (0.3399)   (0.3299)   (0.3443)   (0.2847)   (0.2985)
C(POS)[T.OF]     0.1141     0.0109     0.3398     0.0112     0.1047     0.0214     0.3050
                 (0.2201)   (0.2113)   (0.2267)   (0.1942)   (0.1963)   (0.1803)   (0.1904)
C(POS)[T.SS]     0.0149     -0.2576    0.3633     -0.2724    0.0790     -0.0184    0.5285**
                 (0.2869)   (0.3070)   (0.2957)   (0.2627)   (0.3192)   (0.2415)   (0.2532)
Exp2             -0.0171*** -0.0164**  -0.0091    -0.0084    -0.0013    -0.0014    -0.0078
                 (0.0062)   (0.0073)   (0.0065)   (0.0052)   (0.0051)   (0.0037)   (0.0064)
R-squared        0.5181     0.5513     0.5441     0.5877     0.5125     0.6623     0.5848
R-squared Adj.   0.4703     0.5101     0.5038     0.5507     0.4716     0.6329     0.5422
R-squared        0.52       0.55       0.54       0.59       0.51       0.66       0.58
No. observations 134        144        149        147        156        151        130
=============================================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [180]:
from statsmodels.iolib.summary2 import summary_col
PostMBRate_Out = summary_col([lmrate_Results[14],lmrate_Results[15],lmrate_Results[16],lmrate_Results[17],lmrate_Results[18],
                        lmrate_Results[19],lmrate_Results[20]], model_names=Post_MB, 
                        regressor_order=['BA','ISO_POWER_x','EYE','PA', 'Exp', 'EXP2'],stars=True,info_dict = info_dict)
print(PostMBRate_Out)

===========================================================================================
                    2009       2010      2011      2012       2013       2014       2015
-------------------------------------------------------------------------------------------
BA               7.6219***  7.9516*** 6.2201**  -1.5959    2.7462     5.7890***  5.0992***
                 (2.4116)   (2.7847)  (2.7746)  (2.6167)   (2.1495)   (2.1811)   (1.8966)
ISO_POWER_x      1.6764     2.5375    3.1109**  3.2232**   2.7647*    2.9424**   0.8036
                 (1.4667)   (1.5673)  (1.4932)  (1.6000)   (1.4094)   (1.3941)   (1.5045)
EYE              4.3845**   6.2334*** 4.0906    2.6060     4.1774*    5.8097**   6.0030***
                 (2.1487)   (2.3060)  (2.7579)  (2.5512)   (2.3415)   (2.5174)   (2.1107)
PA               0.0033***  0.0033*** 0.0035*** 0.0042***  0.0032***  0.0032***  0.0033***
                 (0.0005)   (0.0005)  (0.0005)  (0.0006)   (0.0005)   (0.0005)   (0.0004)
Exp              0.0166     0.2109    0.1982    0.0656     -0.0600    0.1719     0.2495
                 (0.1483)   (0.1556)  (0.1483)  (0.1423)   (0.1895)   (0.2014)   (0.1751)
Intercept        10.7617*** 8.9933*** 9.8735*** 12.8252*** 12.8365*** 10.5028*** 10.9428***
                 (0.9933)   (1.2090)  (1.2633)  (1.0809)   (1.2736)   (1.1818)   (1.0966)
C(POS)[T.2B]     -0.1089    0.0035    0.2046    0.1738     -0.5499**  0.3901     -0.3291
                 (0.3495)   (0.3420)  (0.3225)  (0.3226)   (0.2748)   (0.2568)   (0.2425)
C(POS)[T.3B]     0.3158     0.4651    -0.0762   0.4312     -0.2036    0.2050     -0.1491
                 (0.2555)   (0.3045)  (0.3072)  (0.3012)   (0.2614)   (0.2823)   (0.2693)
C(POS)[T.C]      0.6320**   0.1701    0.0726    0.2070     -0.2055    0.2757     -0.3486
                 (0.2730)   (0.3241)  (0.3470)  (0.3352)   (0.2767)   (0.2650)   (0.2244)
C(POS)[T.DH]     0.2828     0.1143    -0.5956*  0.4847     -0.3438    0.3179     -0.1643
                 (0.3487)   (0.3786)  (0.3278)  (0.3884)   (0.3285)   (0.3415)   (0.2580)
C(POS)[T.OF]     0.3645*    0.3890    0.1508    -0.1340    -0.3238    0.4699**   -0.0824
                 (0.2182)   (0.2614)  (0.2571)  (0.2466)   (0.2314)   (0.2153)   (0.1737)
C(POS)[T.SS]     0.5195*    0.6113*   -0.0217   0.1705     -0.3891    0.5716*    0.0542
                 (0.2774)   (0.3469)  (0.3284)  (0.3446)   (0.3313)   (0.2910)   (0.2389)
Exp2             -0.0019    -0.0084   -0.0068   -0.0039    0.0047     -0.0081    -0.0094
                 (0.0063)   (0.0066)  (0.0062)  (0.0059)   (0.0085)   (0.0092)   (0.0080)
R-squared        0.5364     0.4985    0.5160    0.4730     0.5800     0.5232     0.5874
R-squared Adj.   0.4881     0.4488    0.4660    0.4166     0.5291     0.4687     0.5411
R-squared        0.54       0.50      0.52      0.47       0.58       0.52       0.59
No. observations 128        134       129       125        112        118        120
===========================================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# III. Running the Pooled Regression

In [187]:
#Your Code Here
Master_Free = Master_95_15[Master_95_15.Free == 1].copy()
Master_Free['PreMB'] = np.where(Master_Free['SalYear']<=2004,1,0)
Master_Free.describe()

,Unnamed: 0,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,Arb,Free,Catch,Infld,Exp2,BA,ISO_POWER_x,EYE,ISO_POWER_y,PreMB
count,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,...,2841.0,2841.0,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000,2841.000000
mean,3942.336501,2003.809574,1.236536,119.377332,408.487504,59.135164,112.635340,22.287575,1.947906,14.468145,...,0.0,1.0,0.137980,0.322422,109.247800,0.271475,0.163928,0.101523,0.159944,0.489616
std,2269.965795,5.835056,0.712822,30.719136,145.259956,28.484541,45.661153,10.326979,2.182863,11.390127,...,0.0,0.0,0.344939,0.467486,66.079427,0.032331,0.065851,0.037816,0.017855,0.499980
min,8.000000,1994.000000,1.000000,34.000000,130.000000,6.000000,21.000000,1.000000,0.000000,0.000000,...,0.0,1.0,0.000000,0.000000,49.000000,0.147929,0.019608,0.013514,0.104135,0.000000
25%,1983.000000,1999.000000,1.000000,97.000000,283.000000,35.000000,74.000000,14.000000,0.000000,6.000000,...,0.0,1.0,0.000000,0.000000,64.000000,0.250591,0.115632,0.075581,0.148561,0.000000
50%,3950.000000,2004.000000,1.000000,125.000000,428.000000,58.000000,115.000000,21.000000,1.000000,12.000000,...,0.0,1.0,0.000000,0.000000,81.000000,0.272040,0.157895,0.096591,0.160010,0.000000
75%,5901.000000,2009.000000,1.000000,146.000000,535.000000,80.000000,150.000000,30.000000,3.000000,21.000000,...,0.0,1.0,0.000000,1.000000,144.000000,0.293173,0.203774,0.124172,0.172359,1.000000
max,7780.000000,2014.000000,10.000000,163.000000,716.000000,152.000000,227.000000,57.000000,21.000000,73.000000,...,0.0,1.0,1.000000,1.000000,576.000000,0.393795,0.535714,0.390600,0.209782,1.000000

In [188]:
Pooled_lm = smf.ols(formula = 'lnSal ~ BA + ISO_POWER_x + EYE + PA + Exp + Exp2 + C(POS) + PreMB*(BA + ISO_POWER_x + EYE + PA + Exp + Exp2 + C(POS))',\
                    data=Master_Free).fit()
Pooled_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.528
Model:                            OLS   Adj. R-squared:                  0.524
Method:                 Least Squares   F-statistic:                     125.8
Date:                Mon, 14 Nov 2022   Prob (F-statistic):               0.00
Time:                        17:30:55   Log-Likelihood:                -3292.1
No. Observations:                2841   AIC:                             6636.
Df Residuals:                    2815   BIC:                             6791.
Df Model:                          25
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             11.6154      0.307     37.805      0.000      11.013      12.218
C(POS)[T.2B]          -0.1065      0.086     -1.232      0.218      -0.276       0.063
C(POS)[T.3B]           0.1916      0.082      2.340      0.019       0.031       0.352
C(POS)[T.C]            0.1041      0.082      1.262      0.207      -0.058       0.266
C(POS)[T.DH]           0.0375      0.102      0.368      0.713      -0.162       0.237
C(POS)[T.OF]           0.1076      0.067      1.616      0.106      -0.023       0.238
C(POS)[T.SS]           0.1131      0.090      1.254      0.210      -0.064       0.290
BA                     3.0553      0.711      4.295      0.000       1.660       4.450
ISO_POWER_x            2.2644      0.417      5.432      0.000       1.447       3.082
EYE                    3.3354      0.673      4.957      0.000       2.016       4.655
PA                     0.0036      0.000     25.633      0.000       0.003       0.004
Exp                    0.0883      0.042      2.083      0.037       0.005       0.171
Exp2                  -0.0039      0.002     -2.164      0.031      -0.007      -0.000
PreMB                 -0.6385      0.454     -1.407      0.160      -1.528       0.251
PreMB:C(POS)[T.2B]    -0.0812      0.125     -0.647      0.517      -0.327       0.165
PreMB:C(POS)[T.3B]    -0.2720      0.119     -2.283      0.023      -0.506      -0.038
PreMB:C(POS)[T.C]     -0.0343      0.119     -0.288      0.773      -0.268       0.199
PreMB:C(POS)[T.DH]    -0.1477      0.147     -1.008      0.314      -0.435       0.140
PreMB:C(POS)[T.OF]    -0.1005      0.096     -1.051      0.293      -0.288       0.087
PreMB:C(POS)[T.SS]     0.0144      0.130      0.110      0.912      -0.241       0.269
PreMB:BA              -1.1490      1.021     -1.126      0.260      -3.150       0.852
PreMB:ISO_POWER_x      1.1469      0.555      2.066      0.039       0.059       2.235
PreMB:EYE             -1.3491      0.895     -1.508      0.132      -3.103       0.405
PreMB:PA           -7.231e-05      0.000     -0.357      0.721      -0.000       0.000
PreMB:Exp              0.0732      0.064      1.152      0.250      -0.051       0.198
PreMB:Exp2            -0.0037      0.003     -1.353      0.176      -0.009       0.002
==============================================================================
Omnibus:                       22.262   Durbin-Watson:                   1.798
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               32.184
Skew:                           0.062   Prob(JB):                     1.03e-07
Kurtosis:                       3.507   Cond. No.                     4.93e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.93e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""