In [1]:
# install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the data

NBA19 = pd.read_excel("D:\\GitHub\\Coursera\\SportsPerformanceAnalytics\\PredictionModelsWithSportsData\\data\\NBA2019odds.xlsx")
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win
0,Atlanta Hawks,New York Knicks,18,10,2018,2.39,1.60,107,126,0,0,New York Knicks - Atlanta Hawks,126:107,0
1,Atlanta Hawks,Memphis Grizzlies,20,10,2018,3.34,1.34,117,131,0,0,Memphis Grizzlies - Atlanta Hawks,131:117,0
2,Atlanta Hawks,Cleveland Cavaliers,22,10,2018,3.97,1.26,133,111,0,0,Cleveland Cavaliers - Atlanta Hawks,111:133,1
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Washington Wizards,Denver Nuggets,1,4,2019,5.68,1.15,95,90,0,0,Denver Nuggets - Washington Wizards,90:95,1
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0
2458,Washington Wizards,New York Knicks,8,4,2019,1.58,2.44,110,113,0,0,New York Knicks - Washington Wizards,113:110,0
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0

In [3]:
# Calculate the implied win probability from the decimal odds

NBA19['winprob']= 1/(NBA19['winodds'])/(1/(NBA19['winodds'])+ 1/(NBA19['loseodds']))
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
0,Atlanta Hawks,New York Knicks,18,10,2018,2.39,1.60,107,126,0,0,New York Knicks - Atlanta Hawks,126:107,0,0.401003
1,Atlanta Hawks,Memphis Grizzlies,20,10,2018,3.34,1.34,117,131,0,0,Memphis Grizzlies - Atlanta Hawks,131:117,0,0.286325
2,Atlanta Hawks,Cleveland Cavaliers,22,10,2018,3.97,1.26,133,111,0,0,Cleveland Cavaliers - Atlanta Hawks,111:133,1,0.240918
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Washington Wizards,Denver Nuggets,1,4,2019,5.68,1.15,95,90,0,0,Denver Nuggets - Washington Wizards,90:95,1,0.168375
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0,0.807754
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0,0.298475
2458,Washington Wizards,New York Knicks,8,4,2019,1.58,2.44,110,113,0,0,New York Knicks - Washington Wizards,113:110,0,0.606965
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0,0.637019

In [4]:
NBA19 = NBA19[NBA19['home'] != 0]
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,Game(home-away),HAscore,win,winprob
3,Atlanta Hawks,Dallas Mavericks,25,10,2018,2.07,1.79,111,104,0,1,Atlanta Hawks - Dallas Mavericks,111:104,1,0.463731
4,Atlanta Hawks,Chicago Bulls,28,10,2018,1.43,2.91,85,97,0,1,Atlanta Hawks - Chicago Bulls,85:97,0,0.670507
7,Atlanta Hawks,Sacramento Kings,2,11,2018,2.16,1.73,115,146,0,1,Atlanta Hawks - Sacramento Kings,115:146,0,0.444730
8,Atlanta Hawks,Miami Heat,4,11,2018,2.91,1.43,123,118,0,1,Atlanta Hawks - Miami Heat,123:118,1,0.329493
10,Atlanta Hawks,New York Knicks,8,11,2018,2.00,1.83,107,112,0,1,Atlanta Hawks - New York Knicks,107:112,0,0.477807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,Washington Wizards,Denver Nuggets,22,3,2019,4.06,1.26,108,113,0,1,Washington Wizards - Denver Nuggets,108:113,0,0.236842
2451,Washington Wizards,Miami Heat,24,3,2019,1.83,2.02,108,113,0,1,Washington Wizards - Miami Heat,108:113,0,0.524675
2456,Washington Wizards,Chicago Bulls,4,4,2019,1.19,5.00,114,115,0,1,Washington Wizards - Chicago Bulls,114:115,0,0.807754
2457,Washington Wizards,San Antonio Spurs,6,4,2019,3.22,1.37,112,129,0,1,Washington Wizards - San Antonio Spurs,112:129,0,0.298475
2459,Washington Wizards,Boston Celtics,10,4,2019,1.51,2.65,110,116,0,1,Washington Wizards - Boston Celtics,110:116,0,0.637019

In [19]:
NBA19.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,0.110607,-0.160322,-0.021328,0.020338,0.018466,0.008639,0.016095,NaN,0.028164,0.019050
month,0.110607,1.000000,-0.979375,-0.051976,-0.037247,-0.072427,-0.079511,0.037273,NaN,0.026641,0.004125
year,-0.160322,-0.979375,1.000000,0.059743,0.036677,0.068906,0.083059,-0.032301,NaN,-0.029216,-0.009708
winodds,-0.021328,-0.051976,0.059743,1.000000,-0.519700,-0.211101,0.235809,0.022753,NaN,-0.344866,-0.842090
loseodds,0.020338,-0.037247,0.036677,-0.519700,1.000000,0.237857,-0.203061,-0.078881,NaN,0.308797,0.808441
teampts,0.018466,-0.072427,0.068906,-0.211101,0.237857,1.000000,0.344336,0.257128,NaN,0.462650,0.252475
oppopts,0.008639,-0.079511,0.083059,0.235809,-0.203061,0.344336,1.000000,0.306787,NaN,-0.446347,-0.268597
overtime,0.016095,0.037273,-0.032301,0.022753,-0.078881,0.257128,0.306787,1.000000,NaN,-0.027048,-0.056257
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.028164,0.026641,-0.029216,-0.344866,0.308797,0.462650,-0.446347,-0.027048,NaN,1.000000,0.396529
winprob,0.019050,0.004125,-0.009708,-0.842090,0.808441,0.252475,-0.268597,-0.056257,NaN,0.396529,1.000000

In [7]:
# point differential is less than 9
NBA_Less9 = NBA19[abs(NBA19['teampts'] - NBA19['oppopts']) < 9]

In [20]:
NBA_Less9.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,0.106887,-0.152579,-0.040675,0.069440,0.028233,-0.018689,-0.006233,NaN,0.101453,0.059623
month,0.106887,1.000000,-0.980472,-0.012117,-0.057065,-0.095356,-0.117887,0.063516,NaN,0.055742,-0.028230
year,-0.152579,-0.980472,1.000000,0.005980,0.065811,0.109497,0.129969,-0.057381,NaN,-0.050467,0.036246
winodds,-0.040675,-0.012117,0.005980,1.000000,-0.578952,-0.052170,0.059545,0.058482,NaN,-0.193338,-0.879254
loseodds,0.069440,-0.057065,0.065811,-0.578952,1.000000,0.016257,-0.059723,-0.100176,NaN,0.141073,0.828825
teampts,0.028233,-0.095356,0.109497,-0.052170,0.016257,1.000000,0.896585,0.428033,NaN,0.205815,0.031989
oppopts,-0.018689,-0.117887,0.129969,0.059545,-0.059723,0.896585,1.000000,0.432395,NaN,-0.202336,-0.080641
overtime,-0.006233,0.063516,-0.057381,0.058482,-0.100176,0.428033,0.432395,1.000000,NaN,-0.013688,-0.074656
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.101453,0.055742,-0.050467,-0.193338,0.141073,0.205815,-0.202336,-0.013688,NaN,1.000000,0.198116
winprob,0.059623,-0.028230,0.036246,-0.879254,0.828825,0.031989,-0.080641,-0.074656,NaN,0.198116,1.000000

In [8]:
# point differential is greater than 9
NBA_More9 = NBA19[abs(NBA19['teampts'] - NBA19['oppopts']) > 9]

In [21]:
NBA_More9.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,0.120184,-0.174718,0.015962,-0.020077,0.019217,0.009702,0.013059,NaN,-0.014125,-0.025104
month,0.120184,1.000000,-0.978261,-0.090102,-0.016970,-0.043613,-0.055673,-0.046209,NaN,0.019970,0.045479
year,-0.174718,-0.978261,1.000000,0.107757,0.010098,0.026976,0.053651,0.035817,NaN,-0.031787,-0.063591
winodds,0.015962,-0.090102,0.107757,1.000000,-0.501747,-0.303680,0.367279,-0.026428,NaN,-0.475397,-0.833790
loseodds,-0.020077,-0.016970,0.010098,-0.501747,1.000000,0.379109,-0.276493,0.026923,NaN,0.442884,0.798721
teampts,0.019217,-0.043613,0.026976,-0.303680,0.379109,1.000000,-0.029990,0.045192,NaN,0.670262,0.410297
oppopts,0.009702,-0.055673,0.053651,0.367279,-0.276493,-0.029990,1.000000,0.091617,NaN,-0.653095,-0.408580
overtime,0.013059,-0.046209,0.035817,-0.026428,0.026923,0.045192,0.091617,1.000000,NaN,-0.050456,0.042601
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,-0.014125,0.019970,-0.031787,-0.475397,0.442884,0.670262,-0.653095,-0.050456,NaN,1.000000,0.576472
winprob,-0.025104,0.045479,-0.063591,-0.833790,0.798721,0.410297,-0.408580,0.042601,NaN,0.576472,1.000000

In [9]:
# Overtime games
NBA_OT = NBA19[NBA19['overtime'] == 1]

In [22]:
NBA_OT.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,0.027213,-0.038114,-0.216240,0.275625,0.100390,-0.004591,NaN,NaN,0.290799,0.271896
month,0.027213,1.000000,-0.981528,0.044510,0.017936,-0.309640,-0.294500,NaN,NaN,0.001468,0.005750
year,-0.038114,-0.981528,1.000000,-0.034598,-0.014337,0.319084,0.298137,NaN,NaN,0.016086,-0.008926
winodds,-0.216240,0.044510,-0.034598,1.000000,-0.712465,-0.124235,-0.067374,NaN,NaN,-0.059349,-0.917810
loseodds,0.275625,0.017936,-0.014337,-0.712465,1.000000,0.024143,0.016434,NaN,NaN,-0.012001,0.908381
teampts,0.100390,-0.309640,0.319084,-0.124235,0.024143,1.000000,0.929410,NaN,NaN,0.116252,0.071647
oppopts,-0.004591,-0.294500,0.298137,-0.067374,0.016434,0.929410,1.000000,NaN,NaN,-0.202129,0.037730
overtime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.290799,0.001468,0.016086,-0.059349,-0.012001,0.116252,-0.202129,NaN,NaN,1.000000,0.032259
winprob,0.271896,0.005750,-0.008926,-0.917810,0.908381,0.071647,0.037730,NaN,NaN,0.032259,1.000000

In [10]:
# Regulation games
NBA_Reg = NBA19[NBA19['overtime'] == 0]

In [23]:
NBA_Reg.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,0.115044,-0.167201,-0.011925,0.015037,0.009739,0.004436,NaN,NaN,0.012789,0.007058
month,0.115044,1.000000,-0.979236,-0.057686,-0.036104,-0.071906,-0.083167,NaN,NaN,0.029220,0.006264
year,-0.167201,-0.979236,1.000000,0.065251,0.035827,0.066035,0.085133,NaN,NaN,-0.032843,-0.011688
winodds,-0.011925,-0.057686,0.065251,1.000000,-0.517657,-0.229609,0.257146,NaN,NaN,-0.358883,-0.839181
loseodds,0.015037,-0.036104,0.035827,-0.517657,1.000000,0.276582,-0.196401,NaN,NaN,0.318945,0.809366
teampts,0.009739,-0.071906,0.066035,-0.229609,0.276582,1.000000,0.248599,NaN,NaN,0.507802,0.287038
oppopts,0.004436,-0.083167,0.085133,0.257146,-0.196401,0.248599,1.000000,NaN,NaN,-0.476853,-0.281161
overtime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.012789,0.029220,-0.032843,-0.358883,0.318945,0.507802,-0.476853,NaN,NaN,1.000000,0.414435
winprob,0.007058,0.006264,-0.011688,-0.839181,0.809366,0.287038,-0.281161,NaN,NaN,0.414435,1.000000

In [25]:
# 2018 Games
NBA_2018 = NBA19[NBA19['year'] == 2018]

In [26]:
NBA_2018.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,-0.291933,NaN,-0.117968,0.093707,0.076537,0.045858,-0.019835,NaN,0.033941,0.122102
month,-0.291933,1.000000,NaN,0.025453,-0.049268,-0.073787,-0.061571,0.034872,NaN,-0.008495,-0.048380
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,-0.117968,0.025453,NaN,1.000000,-0.586110,-0.203359,0.221029,0.060960,NaN,-0.326073,-0.871581
loseodds,0.093707,-0.049268,NaN,-0.586110,1.000000,0.232770,-0.181776,-0.082372,NaN,0.275301,0.851068
teampts,0.076537,-0.073787,NaN,-0.203359,0.232770,1.000000,0.341215,0.220374,NaN,0.472634,0.249337
oppopts,0.045858,-0.061571,NaN,0.221029,-0.181776,0.341215,1.000000,0.273822,NaN,-0.426843,-0.218721
overtime,-0.019835,0.034872,NaN,0.060960,-0.082372,0.220374,0.273822,1.000000,NaN,-0.042116,-0.065354
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.033941,-0.008495,NaN,-0.326073,0.275301,0.472634,-0.426843,-0.042116,NaN,1.000000,0.338247
winprob,0.122102,-0.048380,NaN,-0.871581,0.851068,0.249337,-0.218721,-0.065354,NaN,0.338247,1.000000

In [11]:
# 2019 Games
NBA_2019 = NBA19[NBA19['year'] == 2019]

In [27]:
NBA_2019.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,-0.203886,NaN,0.047147,-0.015550,-0.005691,0.003626,0.038256,NaN,0.016036,-0.055044
month,-0.203886,1.000000,NaN,0.035237,0.013079,0.002594,0.050367,0.024611,NaN,-0.010655,-0.015797
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.047147,0.035237,NaN,1.000000,-0.495213,-0.227166,0.243815,0.002352,NaN,-0.360023,-0.835435
loseodds,-0.015550,0.013079,NaN,-0.495213,1.000000,0.239871,-0.225756,-0.076260,NaN,0.334621,0.786799
teampts,-0.005691,0.002594,NaN,-0.227166,0.239871,1.000000,0.340204,0.296396,NaN,0.460832,0.257323
oppopts,0.003626,0.050367,NaN,0.243815,-0.225756,0.340204,1.000000,0.345298,NaN,-0.460829,-0.306142
overtime,0.038256,0.024611,NaN,0.002352,-0.076260,0.296396,0.345298,1.000000,NaN,-0.015684,-0.050227
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.016036,-0.010655,NaN,-0.360023,0.334621,0.460832,-0.460829,-0.015684,NaN,1.000000,0.437976
winprob,-0.055044,-0.015797,NaN,-0.835435,0.786799,0.257323,-0.306142,-0.050227,NaN,0.437976,1.000000

In [12]:
NBA_Oct = NBA19[NBA19['month'] == 10]

In [28]:
NBA_Oct.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,0.106227,-0.097936,-0.067056,0.029854,0.034884,NaN,-0.019114,-0.079347
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.106227,NaN,NaN,1.000000,-0.535633,-0.141126,0.351952,-0.037524,NaN,-0.399096,-0.829803
loseodds,-0.097936,NaN,NaN,-0.535633,1.000000,0.194536,-0.176553,-0.073669,NaN,0.314758,0.855516
teampts,-0.067056,NaN,NaN,-0.141126,0.194536,1.000000,0.407989,0.213610,NaN,0.465549,0.210061
oppopts,0.029854,NaN,NaN,0.351952,-0.176553,0.407989,1.000000,0.260017,NaN,-0.414928,-0.294564
overtime,0.034884,NaN,NaN,-0.037524,-0.073669,0.213610,0.260017,1.000000,NaN,-0.054601,-0.012663
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,-0.019114,NaN,NaN,-0.399096,0.314758,0.465549,-0.414928,-0.054601,NaN,1.000000,0.413217
winprob,-0.079347,NaN,NaN,-0.829803,0.855516,0.210061,-0.294564,-0.012663,NaN,0.413217,1.000000

In [13]:
NBA_Nov = NBA19[NBA19['month'] == 11]

In [29]:
NBA_Nov.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,-0.117200,0.149684,0.082676,0.015386,-0.053404,NaN,0.030823,0.131422
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,-0.117200,NaN,NaN,1.000000,-0.626534,-0.284652,0.069406,0.077419,NaN,-0.314411,-0.909629
loseodds,0.149684,NaN,NaN,-0.626534,1.000000,0.278449,-0.102237,-0.113321,NaN,0.254686,0.845098
teampts,0.082676,NaN,NaN,-0.284652,0.278449,1.000000,0.308902,0.193587,NaN,0.539252,0.314361
oppopts,0.015386,NaN,NaN,0.069406,-0.102237,0.308902,1.000000,0.223232,NaN,-0.368895,-0.085978
overtime,-0.053404,NaN,NaN,0.077419,-0.113321,0.193587,0.223232,1.000000,NaN,0.039793,-0.092200
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.030823,NaN,NaN,-0.314411,0.254686,0.539252,-0.368895,0.039793,NaN,1.000000,0.318890
winprob,0.131422,NaN,NaN,-0.909629,0.845098,0.314361,-0.085978,-0.092200,NaN,0.318890,1.000000

In [14]:
NBA_Dec = NBA19[NBA19['month'] == 12]

In [30]:
NBA_Dec.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,-0.176543,0.064395,0.047533,0.023260,0.040108,NaN,0.035291,0.132683
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,-0.176543,NaN,NaN,1.000000,-0.580738,-0.164967,0.287799,0.084037,NaN,-0.300936,-0.866724
loseodds,0.064395,NaN,NaN,-0.580738,1.000000,0.200363,-0.274462,-0.049127,NaN,0.277762,0.855656
teampts,0.047533,NaN,NaN,-0.164967,0.200363,1.000000,0.327860,0.264467,NaN,0.415771,0.198248
oppopts,0.023260,NaN,NaN,0.287799,-0.274462,0.327860,1.000000,0.339047,NaN,-0.491966,-0.321607
overtime,0.040108,NaN,NaN,0.084037,-0.049127,0.264467,0.339047,1.000000,NaN,-0.116314,-0.051470
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.035291,NaN,NaN,-0.300936,0.277762,0.415771,-0.491966,-0.116314,NaN,1.000000,0.321838
winprob,0.132683,NaN,NaN,-0.866724,0.855656,0.198248,-0.321607,-0.051470,NaN,0.321838,1.000000

In [15]:
NBA_Jan = NBA19[NBA19['month'] == 1]

In [31]:
NBA_Jan.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,0.057403,0.027950,-0.089232,0.000693,-0.052547,NaN,-0.051173,-0.034849
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.057403,NaN,NaN,1.000000,-0.533928,-0.233614,0.353196,-0.020781,NaN,-0.453119,-0.886425
loseodds,0.027950,NaN,NaN,-0.533928,1.000000,0.316782,-0.212136,-0.056259,NaN,0.372539,0.780651
teampts,-0.089232,NaN,NaN,-0.233614,0.316782,1.000000,0.279297,0.247676,NaN,0.467900,0.305623
oppopts,0.000693,NaN,NaN,0.353196,-0.212136,0.279297,1.000000,0.337407,NaN,-0.500348,-0.344126
overtime,-0.052547,NaN,NaN,-0.020781,-0.056259,0.247676,0.337407,1.000000,NaN,-0.081133,-0.014340
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,-0.051173,NaN,NaN,-0.453119,0.372539,0.467900,-0.500348,-0.081133,NaN,1.000000,0.503530
winprob,-0.034849,NaN,NaN,-0.886425,0.780651,0.305623,-0.344126,-0.014340,NaN,0.503530,1.000000

In [16]:
NBA_Feb = NBA19[NBA19['month'] == 2]

In [32]:
NBA_Feb.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,0.011214,-0.103977,0.112403,0.082788,0.099962,NaN,0.058596,-0.095096
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.011214,NaN,NaN,1.000000,-0.461893,-0.165634,0.136912,0.059086,NaN,-0.310284,-0.781522
loseodds,-0.103977,NaN,NaN,-0.461893,1.000000,0.232597,-0.162660,-0.115287,NaN,0.326475,0.812194
teampts,0.112403,NaN,NaN,-0.165634,0.232597,1.000000,0.452752,0.298399,NaN,0.466784,0.202714
oppopts,0.082788,NaN,NaN,0.136912,-0.162660,0.452752,1.000000,0.372708,NaN,-0.376673,-0.192476
overtime,0.099962,NaN,NaN,0.059086,-0.115287,0.298399,0.372708,1.000000,NaN,-0.061930,-0.148109
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.058596,NaN,NaN,-0.310284,0.326475,0.466784,-0.376673,-0.061930,NaN,1.000000,0.379280
winprob,-0.095096,NaN,NaN,-0.781522,0.812194,0.202714,-0.192476,-0.148109,NaN,0.379280,1.000000

In [17]:
NBA_Mar = NBA19[NBA19['month'] == 3]

In [33]:
NBA_Mar.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,0.101949,0.053840,0.004897,0.002137,0.069926,NaN,0.017883,-0.040894
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.101949,NaN,NaN,1.000000,-0.543421,-0.222059,0.264971,0.008107,NaN,-0.340895,-0.863310
loseodds,0.053840,NaN,NaN,-0.543421,1.000000,0.136761,-0.226403,-0.081619,NaN,0.292774,0.815421
teampts,0.004897,NaN,NaN,-0.222059,0.136761,1.000000,0.357561,0.364103,NaN,0.446774,0.215464
oppopts,0.002137,NaN,NaN,0.264971,-0.226403,0.357561,1.000000,0.383735,NaN,-0.458364,-0.306884
overtime,0.069926,NaN,NaN,0.008107,-0.081619,0.364103,0.383735,1.000000,NaN,0.022534,-0.049030
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,0.017883,NaN,NaN,-0.340895,0.292774,0.446774,-0.458364,0.022534,NaN,1.000000,0.412708
winprob,-0.040894,NaN,NaN,-0.863310,0.815421,0.215464,-0.306884,-0.049030,NaN,0.412708,1.000000

In [18]:
NBA_Apr = NBA19[NBA19['month'] == 4]

In [34]:
NBA_Apr.corr()

,day,month,year,winodds,loseodds,teampts,oppopts,overtime,home,win,winprob
day,1.000000,NaN,NaN,0.124140,-0.039317,0.043360,0.110439,0.121864,NaN,-0.002422,-0.135538
month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winodds,0.124140,NaN,NaN,1.000000,-0.480059,-0.377069,0.196836,-0.059738,NaN,-0.352581,-0.847809
loseodds,-0.039317,NaN,NaN,-0.480059,1.000000,0.283390,-0.351137,-0.078786,NaN,0.382984,0.754808
teampts,0.043360,NaN,NaN,-0.377069,0.283390,1.000000,0.245022,0.271505,NaN,0.480868,0.337300
oppopts,0.110439,NaN,NaN,0.196836,-0.351137,0.245022,1.000000,0.240642,NaN,-0.518904,-0.400337
overtime,0.121864,NaN,NaN,-0.059738,-0.078786,0.271505,0.240642,1.000000,NaN,0.096077,-0.003960
home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
win,-0.002422,NaN,NaN,-0.352581,0.382984,0.480868,-0.518904,0.096077,NaN,1.000000,0.455436
winprob,-0.135538,NaN,NaN,-0.847809,0.754808,0.337300,-0.400337,-0.003960,NaN,0.455436,1.000000